# This file was generated by GoReleaser. DO NOT EDIT.
cask "bifrost-quota-monitor" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "9ab3d7e62f42297d4741b713cf33b74b7372ba832e73cd7d405c2e1037fd5727"
      url "https://github.com/censys/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f3d366589edcc22b0402ffd6d05592202b5201705ec0aa7a87dcb95ee95d3fb0"
      url "https://github.com/censys/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6e33f150e4db461a75dcf2c2ab80d6923c201dde0da1ec7338841095f789c604"
      url "https://github.com/censys/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "fbc6dff8e71b85fa13ac58275bba6cc335c8169445fb44a80971c959197f6481"
      url "https://github.com/censys/bifrost-quota-monitor/releases/download/v#{version}/bifrost-quota-monitor_#{version}_linux_amd64.tar.gz"
    end
  end

  name "bifrost-quota-monitor"
  desc "tmux status bar segment showing Bifrost virtual key budget usage"
  homepage "https://github.com/censys/bifrost-quota-monitor"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "bifrost-quota-monitor"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/bifrost-quota-monitor"]
      # An upgrade swaps the binary but leaves the running agent on the old
      # one, since nothing here manages launchd. Restart it when init has
      # already installed the agent, and stay quiet when it has not.
      label = "com.github.censys.bifrost-quota-monitor"
      if File.exist?(File.expand_path("~/Library/LaunchAgents/#{label}.plist"))
        system_command "/bin/launchctl",
                       args: ["kickstart", "-k", "gui/#{Process.uid}/#{label}"],
                       must_succeed: false
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Set BIFROST_BASE_URL and BIFROST_API_KEY, then run 'bifrost-quota-monitor init' to install the launchd agent and patch your tmux config. There is no default gateway address, since Bifrost is self-hosted. See https://github.com/censys/bifrost-quota-monitor for setup and troubleshooting.
  EOS
end
