# This file was generated by GoReleaser. DO NOT EDIT.
cask "cencli" do
  version "1.0.12"

  on_macos do
    on_intel do
      sha256 "ed27ace154b7b894e22c37412e61297cd80a8781b53e5b48978610d56469d78f"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
    on_arm do
      sha256 "ea1df38fd016e13bef36d67a22db041727b2e99c1cb24ae3b5559ad6881f7cfd"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "96cded68db681b5ad4be2ff9e0ce53659d4614fa087aab6a5db8630d428c0125"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
    on_arm do
      sha256 "56c168c39d63077c9a1e8650ba671760c719506a2af794fcc657fb49c265c5ab"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
  end

  name "cencli"
  desc "Censys CLI"
  homepage "https://github.com/censys/cencli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "censys"
  bash_completion "completions/censys.bash"
  zsh_completion "completions/_censys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/censys"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    NOTE: the installed executable is 'censys', not 'cencli'. For more info, visit https://docs.censys.com/docs/platform-cli.
  EOS
end
