# This file was generated by GoReleaser. DO NOT EDIT.
cask "cencli" do
  version "1.0.8"

  on_macos do
    on_intel do
      sha256 "4dd83d24be3be3255268c7e8ad9d150cef77c8e9ebc68a96ac1342fa3b74d3ce"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
    on_arm do
      sha256 "0f0a67ba22ebba70cad9d2e92b6610639665c66a50dfa8505bc80f96762002f8"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "7968e8c54b33562e0ae2cdc9a9597ebb57e2837a5d4d74eab4c692ee33538e4a"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
    on_arm do
      sha256 "4796213bc1d5a2f99395da4ebec09b067230abceb7602bb625ede63ebb304762"
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/censys/cencli/"
    end
  end

  name "cencli"
  desc "Censys CLI"
  homepage "https://github.com/censys/cencli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "censys"
  bash_completion "completions/censys.bash"
  zsh_completion "completions/_censys"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/censys"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    NOTE: the installed executable is 'censys', not 'cencli'. For more info, visit https://docs.censys.com/docs/platform-cli.
  EOS
end
