# This file was generated by GoReleaser. DO NOT EDIT.
cask "cencli" do
  name "cencli"
  desc "Censys CLI"
  homepage "https://github.com/censys/cencli"
  version "0.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "censys"
  bash_completion "completions/censys.bash"
  zsh_completion "completions/_censys"

  on_macos do
    on_intel do
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/censys/cencli/"
      sha256 "16d7f997c805a3b29fb03eb9430c4c0f3752e20ca4a89075d128d31491a8acc3"
    end
    on_arm do
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/censys/cencli/"
      sha256 "56a27f035a5aad5b78d0aa93634b758d132a340b480c15be7e58b8897555af51"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_linux_amd64.tar.gz",
        verified: "github.com/censys/cencli/"
      sha256 "84111a8782cd50a1b84889a2a4d095d84f13a27e5fdbeb9200ec141126d990a8"
    end
    on_arm do
      url "https://github.com/censys/cencli/releases/download/v#{version}/cencli_#{version}_linux_arm64.tar.gz",
        verified: "github.com/censys/cencli/"
      sha256 "d39e1fc87113b2513dff04969ef95c8282a899c3e8ef531ebf65b9b753b18354"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/censys"]
    end
  end

  caveats do
    "NOTE: the installed executable is 'censys', not 'cencli'. For more info, visit https://docs.censys.com/docs/platform-cli."
  end

  # No zap stanza required
end
